port: 5000

# define duration between each dashboard rotation (s)
rotationDuration: 25
# define the interval used by Mozaïk Bus to call registered APIs
apisPollInterval: 70000

dashboards:
- columns: 5
  rows:    4
  title:   OXEN dashboard
  widgets:
    -
      extension:      loki
      widget:         CustomJson
      url:            http://88.208.54.18:9000/loki-price
      title:          Current Price
      template:       "<div class='json-w-wrapper'>
                        <div class='json-w-center'>
                          <div class='json-w-big-text'>$<%= _.round(data.LOKI.quote.USD.price, 3) %></div>
                          <div class='json-w-right-text' style='color: <%= data.LOKI.quote.USD.percent_change_1h < 0 ? 'red' : 'green' %>'>
                            <%= _.round(data.LOKI.quote.USD.percent_change_1h, 2) %>%&nbsp;<%= data.LOKI.quote.USD.percent_change_1h < 0 ? '↓' : '↑' %>
                          </div>
                        </div>
                        <div class='json-w-bottom-text'><%= _.round(data.LOKI.quote.BTC.price * 100000000, 2) %> Satoshi</div>
                      </div>"
      columns:        1
      rows:           2
      x:              0
      y:              0
    -
      extension:      loki
      widget:         CustomJson
      url:            http://88.208.54.18:9000/loki-stats
      title:          Current Mempool size
      template:       "<div class='json-w-wrapper'>
                        <div class='json-w-center'>
                          <div class='json-w-big-text'><%= currentMempoolSize %></div>
                        </div>
                        <div class='json-w-bottom-text'>24 hrs average: <%= _.round(averageMempoolSize, 2) %></div>
                      </div>"
      columns:        1
      rows:           1
      x:              0
      y:              2
    -
      extension:      loki
      widget:         CustomJson
      url:            http://88.208.54.18:9000/loki-stats
      title:          Average tx in block, 30 days
      template:       "<div class='json-w-wrapper'>
                        <div class='json-w-center'>
                          <div class='json-w-big-text'><%= _.round(averageTransactionsInBlock, 2) %></div>
                        </div>
                      </div>"
      columns:        1
      rows:           1
      x:              0
      y:              3
    -
      extension:      loki
      widget:         MedianBlockSizeGraph
      url:            http://88.208.54.18:9000/loki-stats
      title:          Median block size
      columns:        2
      rows:           2
      x:              1
      y:              0
    -
      extension:      loki
      widget:         AlternateChainCountGraph
      url:            http://88.208.54.18:9000/loki-stats
      title:          Alternate Chain Count
      columns:        2
      rows:           2
      x:              3
      y:              0
    -
      extension:      loki
      widget:         BlockchainSizeGraph
      url:            http://88.208.54.18:9000/loki-stats
      title:          Blockchain size
      columns:        2
      rows:           2
      x:              1
      y:              2
    -
      extension:      loki
      widget:         MinorMajorVersionsGraph
      url:            http://88.208.54.18:9000/loki-stats
      title:          Minor & Major versions (24h)
      columns:        2
      rows:           2
      x:              3
      y:              2
- columns: 2
  rows:    2
  title:   Oxen Hashrate & Block Time
  widgets:
    -
      extension:      loki
      widget:         EmissionGraph
      url:            http://88.208.54.18:9000/loki-stats
      param:          emissionCumulative
      title:          Circulating Supply
      columns:        1
      rows:           1
      x:              0
      y:              0
    -
      extension:      loki
      widget:         EmissionGraph
      url:            http://88.208.54.18:9000/loki-stats
      param:          emission
      title:          Emission per day (30d)
      columns:        1
      rows:           1
      x:              1
      y:              0
    -
      extension:      loki
      widget:         HashrateGraph
      url:            http://88.208.54.18:9000/loki-stats
      title:          Network hashrate (lifetime)
      columns:        1
      rows:           1
      x:              0
      y:              1
    -
      extension:      loki
      widget:         BlockTimeHistogram
      url:            http://88.208.54.18:9000/loki-stats
      title:          Blocktime freq. distribution
      columns:        1
      rows:           1
      x:              1
      y:              1
- columns: 2
  rows:    2
  title:   Emission, Fees and Burn
  widgets:
  - 
    extension:      loki
    widget:         EmissionGraph
    url:            http://88.208.54.18:9000/loki-stats
    param:          feeCumulative
    title:          Fee Cumulative
    columns:        1
    rows:           1
    x:              0
    y:              0
  - 
    extension:      loki
    widget:         EmissionGraph
    url:            http://88.208.54.18:9000/loki-stats
    param:          burnCumulative
    title:          Burn Cumulative
    columns:        1
    rows:           1
    x:              1
    y:              0
  - 
    extension:      loki
    widget:         EmissionGraph
    url:            http://88.208.54.18:9000/loki-stats
    param:          fee
    title:          Fee per day (30d)
    columns:        1
    rows:           1
    x:              0
    y:              1
  - 
    extension:      loki
    widget:         EmissionGraph
    url:            http://88.208.54.18:9000/loki-stats
    param:          burn
    title:          Burn per day (30d)
    columns:        1
    rows:           1
    x:              1
    y:              1
- columns: 6
  rows:    2
  title:   OXEN Service Nodes
  widgets:
    -
      extension:      loki
      widget:         NumOfSnGraph
      url:            http://88.208.54.18:9000/loki-stats
      title:          Service node count 
      columns:        3
      rows:           1
      x:              0
      y:              0
    -
      extension:      loki
      widget:         CustomJson
      url:            http://88.208.54.18:9000/loki-sn-calc
      title:          SN Locked,% of circ. supply
      template:       "<div class='json-w-wrapper'>
                        <div class='json-w-center'>
                          <div class='json-w-big-text'><%= _.round(contributedToCircSupplyPercent ? contributedToCircSupplyPercent : 0, 1) %>%</div>
                        </div>
                      </div>"
      columns:        1
      rows:           1
      x:              3
      y:              0
    -
      extension:      loki
      widget:         SNStateChanges
      url:            http://88.208.54.18:9000/loki-sn-calc
      title:          SN State Changes (30 days)
      columns:        2
      rows:           1
      x:              4
      y:              0
    -
      extension:      loki
      widget:         StakingGraph
      url:            http://88.208.54.18:9000/loki-sn-calc
      title:          Current Staking amount required
      columns:        3
      rows:           1
      x:              0
      y:              1
    -
      extension:      loki
      widget:         SnVersionGraph
      url:            http://88.208.54.18:9000/loki-sn-calc
      title:          SN versions 
      columns:        3
      rows:           1
      x:              3
      y:              1
- columns: 13
  rows:    1
  title:   Nodes Distribution
  widgets:
    -
      extension:      loki
      widget:         NodesDistributionCountries
      url:            http://88.208.54.18:9000/loki-node-distribution
      title:          Countries
      columns:        3
      rows:           1
      x:              0
      y:              0
    -
      extension:      loki
      widget:         NodesDistributionAsn
      url:            http://88.208.54.18:9000/loki-node-distribution
      title:          Network Owners
      columns:        4
      rows:           1
      x:              3
      y:              0
    -
      extension:      loki
      widget:         NodesDistribution
      url:            http://88.208.54.18:9000/loki-node-distribution
      title:          Map
      columns:        6
      rows:           1
      x:              7
      y:              0