port: 5000

# define duration between each dashboard rotation (ms)
rotationDuration: 10000
# define the interval used by Mozaïk Bus to call registered APIs
apisPollInterval: 100000

dashboards:
- columns: 3
  rows:    3
  title:   LOKI dashboard
  widgets:
    -
      extension:      loki
      widget:         CustomJson
      url:            http://88.208.54.18:9000/loki-sn-calc
      title:          Service node count 
      template:       "<div class='json-w-wrapper'>
                        <div class='json-w-center'>
                          <div class='json-w-big-text'><%= numOfSNs %></div>
                        </div>
                      </div>"
      columns:        1
      rows:           1
      x:              1
      y:              0
    -
      extension:      loki
      widget:         CustomJson
      url:            http://88.208.54.18:9000/loki-sn-calc
      title:          SN Locked,% of circ. supply
      template:       "<div class='json-w-wrapper'>
                        <div class='json-w-center'>
                          <div class='json-w-big-text'><%= _.round(contributedToCircSupplyPercent, 2) %>%</div>
                        </div>
                      </div>"
      columns:        1
      rows:           1
      x:              2
      y:              0
    -
      extension:      loki
      widget:         StakingGraph
      url:            http://88.208.54.18:9000/loki-sn-calc
      title:          Current Staking amount required
      columns:        2
      rows:           2
      x:              0
      y:              1